# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SummaryExperiences' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry', '~> 1.0.2'
pod 'RATreeView', '~> 2.1.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'JSONKit-NoWarning','~>1.2'
pod 'MJRefresh', '~>3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 3.8.1'
pod 'RATreeView', '~>2.1.0'
pod 'LYPickerChiceView', '~> 0.0.3'


end
